
name: workflow-test

on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  test-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: echo hello!
